### ISSUE TITLE
multiprocessing.pool.MaybeEncodingError

### ISSUE THREAD

**Issue by htmlboss** [ioos/thredds_crawler#25]
Using Anaconda w/ Python 3.6, I am now getting the following exception:
```python
Traceback (most recent call last):
  File "/opt/tools/anaconda2/envs/testpy/lib/python3.6/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/tools/anaconda2/envs/testpy/lib/python3.6/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/opt/tools/anaconda2/envs/testpy/lib/python3.6/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/tools/anaconda2/envs/testpy/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/opt/tools/anaconda2/envs/testpy/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/tools/anaconda2/envs/testpy/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/tools/anaconda2/envs/testpy/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/tools/anaconda2/envs/testpy/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/opt/tools/anaconda2/envs/testpy/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/tools/anaconda2/envs/testpy/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/nabil/Ocean-Data-Map-Project/oceannavigator/views.py", line 81, in query
    data = oceannavigator.misc.list_class4_files()
  File "/home/nabil/Ocean-Data-Map-Project/oceannavigator/misc.py", line 531, in list_class4_files
    return list_class4_files_slowly()
  File "/home/nabil/Ocean-Data-Map-Project/oceannavigator/misc.py", line 499, in list_class4_files_slowly
    workers=8, debug=True)
  File "/opt/tools/anaconda2/envs/testpy/lib/python3.6/site-packages/thredds_crawler/crawl.py", line 120, in __init__
    datasets = [j.get() for j in jobs]
  File "/opt/tools/anaconda2/envs/testpy/lib/python3.6/site-packages/thredds_crawler/crawl.py", line 120, in <listcomp>
    datasets = [j.get() for j in jobs]
  File "/opt/tools/anaconda2/envs/testpy/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
multiprocessing.pool.MaybeEncodingError: Error sending result: '<LeafDataset id: class4/class4_20180420_GIOPS_CONCEPTS_2.3_profile.nc, name: class4_20180420_GIOPS_CONCEPTS_2.3_profile.nc, services: ['OPENDAP', 'DAP4', 'HTTPServer', 'NetcdfSubset', 'WMS']>'. Reason: 'TypeError("can't pickle lxml.etree._Element objects",)'

```

Python 2.7 had no issues. The datasets themselves have not changed.
Any ideas?

**Comment by MBARIMike** [comment]
I encountered same error, but am not using conda (yet) can 1.5.4 be pushed to PyPI?

**Comment by kwilcox** [comment]
@MBARIMike sure. In the interim you can install with `pip install git+https://github.com/ioos/thredds_crawler.git`.

**Comment by kwilcox** [comment]
@MBARIMike I just uploaded `1.5.4` to pypi. Let me know if you have troubles.

**Comment by MBARIMike** [comment]
1.5.4 fixed the error and my pyup-bot thinks it's O.K.: https://github.com/MBARIMike/stoqs/pull/336 Thanks!
